[package]
name = "traitor"
version = "0.1.0"
authors = ["Jos <gnu.crazier@gmail.com>"]

[dependencies]
toml = "0.2"
rust-crypto = "^0.2"
hyper = "0.9.10"
random = "0.12.1"
rustc-serialize = "0.3"
urlencode = { path = "urlencode" }
